[[redirects]]
    from = "https://friendly-shannon-fbae91.netlify.app/testpage"
    from = "https://friendly-shannon-fbae91.netlify.app/resultpage"
    to = "https://friendly-shannon-fbae91.netlify.app/"
    status = 200

